/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * FAQs - A simple class to display frequently asked questions and answers
 * @author kudamlambo
 */
public class faqs extends javax.swing.JFrame {
    
    public faqs() {
        initComponents();
        loadFAQs();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        faqArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frequently Asked Questions - HistoryEd");
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainPanel.setBackground(new java.awt.Color(255, 153, 51));
        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 153, 51));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Frequently Asked Questions");
        headerPanel.add(titleLabel, java.awt.BorderLayout.WEST);

        btnBack.setPreferredSize(new java.awt.Dimension(120, 35));
        btnBack.setText("Back to Menu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        headerPanel.add(btnBack, java.awt.BorderLayout.EAST);

        mainPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));

        faqArea.setBackground(new java.awt.Color(255, 255, 255));
        faqArea.setEditable(false);
        faqArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        faqArea.setLineWrap(true);
        faqArea.setWrapStyleWord(true);
        scrollPane.setViewportView(faqArea);

        mainPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new Menu1().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    
    /**
     * Load and display frequently asked questions
     */
    private void loadFAQs() {
        StringBuilder sb = new StringBuilder();
        
        sb.append("FREQUENTLY ASKED QUESTIONS\n");
        sb.append("=".repeat(50)).append("\n\n");
        
        // FAQ 1: How to use the application
        sb.append("1. HOW DO I USE THE HISTORYED APPLICATION?\n");
        sb.append("   Answer: HistoryEd is an educational application designed to help students learn history.\n");
        sb.append("   • Use the Notes section to read educational content by grade level\n");
        sb.append("   • Take quizzes to test your knowledge in the Quiz section\n");
        sb.append("   • View your results in the View Results section\n");
        sb.append("   • Access FAQs for help and guidance\n\n");
        
        // FAQ 2: How to take quizzes
        sb.append("2. HOW DO I TAKE A QUIZ?\n");
        sb.append("   Answer: To take a quiz:\n");
        sb.append("   • Click on the 'Quiz' button in the main menu\n");
        sb.append("   • Select your grade level and topic\n");
        sb.append("   • Read each question carefully\n");
        sb.append("   • Select your answer from the multiple choice options\n");
        sb.append("   • Use 'Previous' and 'Next' buttons to navigate\n");
        sb.append("   • Click 'Finish Quiz' when you're done\n");
        sb.append("   • View your results immediately after completion\n\n");
        
        // FAQ 3: How to view results
        sb.append("3. HOW DO I VIEW MY QUIZ RESULTS?\n");
        sb.append("   Answer: To view your results:\n");
        sb.append("   • Click on 'View Results' in the main menu\n");
        sb.append("   • Select whether you are a 'Student' or 'Teacher'\n");
        sb.append("   • If you're a student, enter your email address\n");
        sb.append("   • Your results will be displayed with scores and percentages\n");
        sb.append("   • Teachers can view all student results\n\n");
        
        // FAQ 4: How to access notes
        sb.append("4. HOW DO I ACCESS EDUCATIONAL NOTES?\n");
        sb.append("   Answer: To access notes:\n");
        sb.append("   • Click on the 'Notes' button in the main menu\n");
        sb.append("   • Select your grade level (G8, G9, G10, G11, or G12)\n");
        sb.append("   • Choose the specific topic you want to study\n");
        sb.append("   • Read through the educational content\n");
        sb.append("   • Use the back button to return to the main menu\n\n");
        
        // FAQ 5: Grade levels and topics
        sb.append("5. WHAT GRADE LEVELS AND TOPICS ARE AVAILABLE?\n");
        sb.append("   Answer: The application covers:\n");
        sb.append("   • Grade 8: Industrial Revolution, Mineral Revolution, Scramble for Africa, World War I\n");
        sb.append("   • Grade 9: Cold War, World War II, Turning Points in South African History\n");
        sb.append("   • Grade 10: Colonial Expansion, French Revolution, 15th & 16th Centuries, Transformations\n");
        sb.append("   • Grade 11: Apartheid, Capitalism, Communism, Ideas of Race\n");
        sb.append("   • Grade 12: Civil Resistance, Civil Society Protests\n\n");
        
        // FAQ 6: Teacher access
        sb.append("6. HOW DO TEACHERS USE THE APPLICATION?\n");
        sb.append("   Answer: Teachers can:\n");
        sb.append("   • View all student quiz results\n");
        sb.append("   • Monitor student progress across topics\n");
        sb.append("   • Access educational content for lesson planning\n");
        sb.append("   • Use the application as a teaching tool\n");
        sb.append("   • Track class performance and identify areas for improvement\n\n");
        
        // FAQ 7: Contact information
        sb.append("7. HOW CAN I GET MORE HELP?\n");
        sb.append("    Answer: For additional support:\n");
        sb.append("    • Ask your teacher for guidance\n");
        sb.append("    • Review the notes section for detailed explanations\n");
        sb.append("    • Practice with quizzes to improve understanding\n");
        sb.append("    • Use the application regularly to build knowledge\n\n");
        
        sb.append("Thank you for using HistoryEd!\n");
        sb.append("We hope this application helps you learn and succeed in your history studies.\n");
        
        faqArea.setText(sb.toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new faqs().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextArea faqArea;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
} 