
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 25kudakwashem
 */
public class SignUp extends javax.swing.JFrame {
    private final Login role;
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        role = new Login();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLLogo = new javax.swing.JLabel();
        LBLFname = new javax.swing.JLabel();
        LBLSurname = new javax.swing.JLabel();
        LBLAddress = new javax.swing.JLabel();
        LBLPassword = new javax.swing.JLabel();
        LBLRole = new javax.swing.JLabel();
        txfFname = new javax.swing.JTextField();
        txfSurname = new javax.swing.JTextField();
        txfAddress = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        BtnSignUp = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        CMBRole = new javax.swing.JComboBox<>();
        LBLfNameStatus = new javax.swing.JLabel();
        LBLSnameStatus = new javax.swing.JLabel();
        LBLCellNo = new javax.swing.JLabel();
        txfCellNo = new javax.swing.JTextField();
        LBLCellNoStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLLogo.setFont(new java.awt.Font("Bauhaus 93", 3, 36)); // NOI18N
        LBLLogo.setForeground(new java.awt.Color(255, 153, 51));
        LBLLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLLogo.setText("Welcome to HistoryEd ");

        LBLFname.setText("First Name:");

        LBLSurname.setText("Surname: ");

        LBLAddress.setText("E-mail Address:");

        LBLPassword.setText("Password: ");

        LBLRole.setText("Role:");

        txfSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSurnameActionPerformed(evt);
            }
        });

        BtnSignUp.setText("Sign Up");
        BtnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignUpActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        CMBRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select your role", "Student", "Teacher", "" }));
        CMBRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBRoleActionPerformed(evt);
            }
        });

        LBLCellNo.setText("Cell Number");

        txfCellNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCellNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LBLLogo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLFname)
                                    .addComponent(LBLRole)
                                    .addComponent(LBLSurname)
                                    .addComponent(LBLPassword)
                                    .addComponent(LBLAddress)
                                    .addComponent(LBLCellNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfFname)
                                    .addComponent(txfSurname)
                                    .addComponent(txfAddress)
                                    .addComponent(txfPassword)
                                    .addComponent(CMBRole, 0, 150, Short.MAX_VALUE)
                                    .addComponent(txfCellNo)))))
                    .addComponent(BtnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBLfNameStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLSnameStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLCellNoStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LBLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLFname)
                            .addComponent(txfFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLSurname)
                            .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLSnameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLAddress)
                            .addComponent(txfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLPassword)
                            .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLRole)
                            .addComponent(CMBRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLCellNo)
                            .addComponent(txfCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLCellNoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(BtnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBLfNameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignUpActionPerformed
        String fName = txfFname.getText();
        String sName = txfSurname.getText();
        String email = txfAddress.getText();
        String pass = txfPassword.getText();           
        String role = CMBRole.getSelectedItem().toString();
        String cellNo = txfCellNo.getText();
        
        //email search
        String filePath =  "UserDetails.txt";
        try {
            Scanner scFile = new Scanner(new File(filePath));
           
            while (scFile.hasNextLine()) {
                Scanner scLine = new Scanner(scFile.nextLine()).useDelimiter("#");
                scLine.next();
                scLine.next();
                String emailInFile = scLine.next();
                
                if (emailInFile.equalsIgnoreCase(email)) {
                    JOptionPane.showMessageDialog(null, "You have already signed up using the entered email");
                    this.setVisible(false);
                    Login loginScreen = new Login();
                    loginScreen.setVisible(true);
                    return; // Stop further execution if email is found
                }
            }
            
        } catch (FileNotFoundException ex) {
            System.out.println("File Not Found!");
        }
        
        
        
        
        //Validation check 
        //fName - Presence check
        if (fName.length() == 0) 
        {
           LBLfNameStatus.setText("Please enter a name");
           txfFname.setBackground(Color.red);
           
        }
        else
        {
            LBLfNameStatus.setText("Entered");
            txfFname.setBackground(Color.green);
        }
       
        
        //surname - Presence check
        if (sName.length() == 0) 
        {
            LBLSnameStatus.setText("Please enter a surname"); 
            txfSurname.setBackground(Color.red);
        }
        else
        {
            LBLSnameStatus.setText("Surname has been entered"); 
            txfSurname.setBackground(Color.green);
        }
        
        //cellNo - length check
        if (cellNo.length() == 10) 
        {
            LBLCellNoStatus.setText("Number is valid"); 
            txfCellNo.setBackground(Color.green);
        }
        else
        {
            LBLCellNoStatus.setText("Number must be 10 digits"); 
            txfCellNo.setBackground(Color.red);
        
        
        String textToAdd =fName+"#"+sName+"#"+email+"#"+pass+"#"+role+"#"+cellNo+"\n";
        
        String wordToCheck = "war"; // 🔍 Word to search for (case-insensitive)
        int wordCount = 0;
            
        try 
        {
            //write user's details into text file
            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath, true));
            writer.write(textToAdd);
            writer.close();
            JOptionPane.showMessageDialog(null,"You have successfully signed up");
            
            //Add new information to textfile
            this.setVisible(false);
            new Menu1().setVisible(true);
        } 
        
        catch (IOException e) 
        {
            JOptionPane.showMessageDialog(null, "Please try again");
           
        }
            
        
       }
    }//GEN-LAST:event_BtnSignUpActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        this.setVisible(false);
        new HistoryED().setVisible(true);        
    }//GEN-LAST:event_BtnBackActionPerformed

    private void txfSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSurnameActionPerformed

    private void CMBRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBRoleActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_CMBRoleActionPerformed

    private void txfCellNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCellNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCellNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSignUp;
    private javax.swing.JComboBox<String> CMBRole;
    private javax.swing.JLabel LBLAddress;
    private javax.swing.JLabel LBLCellNo;
    private javax.swing.JLabel LBLCellNoStatus;
    private javax.swing.JLabel LBLFname;
    private javax.swing.JLabel LBLLogo;
    private javax.swing.JLabel LBLPassword;
    private javax.swing.JLabel LBLRole;
    private javax.swing.JLabel LBLSnameStatus;
    private javax.swing.JLabel LBLSurname;
    private javax.swing.JLabel LBLfNameStatus;
    private javax.swing.JTextField txfAddress;
    private javax.swing.JTextField txfCellNo;
    private javax.swing.JTextField txfFname;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfSurname;
    // End of variables declaration//GEN-END:variables
}
