/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import java.io.*;
import java.util.Scanner;

/**
 *
 * @author kudamlambo
 */
public class StudentResultsDisplay extends javax.swing.JFrame {

    // Data storage for student results
    private String[] studentResults;
    private int resultCount;
    
    /**
     * Creates new form Notes
     */
    public StudentResultsDisplay() {
        initComponents();
        studentResults = new String[1000]; // Simple array for IEB Grade 12
        resultCount = 0;
        loadStudentResults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLlogo = new javax.swing.JLabel();
        BtnHelp = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BtnNotes = new javax.swing.JButton();
        BtnQuiz = new javax.swing.JButton();
        BtnFAQs = new javax.swing.JButton();
        BtnSettings = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LBLLogo2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setForeground(new java.awt.Color(255, 153, 51));

        LBLlogo.setFont(new java.awt.Font("Apple Chancery", 3, 48)); // NOI18N
        LBLlogo.setText("Results");

        BtnHelp.setBackground(new java.awt.Color(255, 153, 51));
        BtnHelp.setText("?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnHelp)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBLlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LBLlogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnHelp))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        BtnNotes.setBackground(new java.awt.Color(0, 0, 0));
        BtnNotes.setForeground(new java.awt.Color(255, 255, 255));
        BtnNotes.setText("Notes");
        BtnNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNotesActionPerformed(evt);
            }
        });

        BtnQuiz.setBackground(new java.awt.Color(0, 0, 0));
        BtnQuiz.setForeground(new java.awt.Color(255, 255, 255));
        BtnQuiz.setText("Quiz");
        BtnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuizActionPerformed(evt);
            }
        });

        BtnFAQs.setBackground(new java.awt.Color(0, 0, 0));
        BtnFAQs.setForeground(new java.awt.Color(255, 255, 255));
        BtnFAQs.setText("FAQs");
        BtnFAQs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFAQsActionPerformed(evt);
            }
        });

        BtnSettings.setBackground(new java.awt.Color(0, 0, 0));
        BtnSettings.setForeground(new java.awt.Color(255, 255, 255));
        BtnSettings.setText("Log Out");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(BtnFAQs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(BtnQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(BtnFAQs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(BtnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        LBLLogo2.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        LBLLogo2.setText("Student Quiz Results");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(LBLLogo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LBLLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNotesActionPerformed
        this.setVisible(false);
        new Notes().setVisible(true);
    }//GEN-LAST:event_BtnNotesActionPerformed

    private void BtnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuizActionPerformed
        this.setVisible(false);
        new QuizDisplay().setVisible(true);
    }//GEN-LAST:event_BtnQuizActionPerformed

    private void BtnFAQsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFAQsActionPerformed
        this.setVisible(false);
        new faqs().setVisible(true);
    }//GEN-LAST:event_BtnFAQsActionPerformed

    private void BtnViewResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewResultsActionPerformed
        // Ask user if they are a teacher or student
        String[] options = {"Teacher", "Student"};
        int choice = JOptionPane.showOptionDialog(this, 
            "Are you a teacher or student?", 
            "Select Role", 
            JOptionPane.DEFAULT_OPTION, 
            JOptionPane.QUESTION_MESSAGE, 
            null, 
            options, 
            options[0]);
        
        if (choice == 0) {
            // Teacher
            this.setVisible(false);
            new TeacherResultsViewer().setVisible(true);
        } else if (choice == 1) {
            // Student - prompt for email
            String email = JOptionPane.showInputDialog(this, 
                "Enter your email address:", 
                "Student Email", 
                JOptionPane.QUESTION_MESSAGE);
            
            if (email != null && !email.trim().isEmpty()) {
                this.setVisible(false);
                new StudentResultsViewer(email.trim()).setVisible(true);
            }
        }
    }//GEN-LAST:event_BtnViewResultsActionPerformed

    private void comboFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFilterActionPerformed
        filterResults();
    }//GEN-LAST:event_comboFilterActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadStudentResults();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * Load student results from the QuizResults.txt file using Scanner
     */
    private void loadStudentResults() {
        resultCount = 0;
        
        try {
            Scanner fileScanner = new Scanner(new File("TextFiles/QuizResults.txt"));
            
            while (fileScanner.hasNextLine()) {
                String line = fileScanner.nextLine();
                
                if (!line.equals("")) {
                    String[] parts = line.split("#");
                    if (parts.length >= 2) {
                        String email = parts[0];
                        
                        for (int i = 1; i < parts.length; i++) {
                            String result = parts[i];
                            String[] resultParts = result.split("-");
                            
                            if (resultParts.length >= 3) {
                                String grade = resultParts[0];
                                String topic = resultParts[1];
                                String score = resultParts[2];
                                
                                String quizTopic = grade + "-" + topic;
                                
                                // Calculate percentage
                                String[] scoreParts = score.split("/");
                                if (scoreParts.length == 2) {
                                    int correct = Integer.parseInt(scoreParts[0]);
                                    int total = Integer.parseInt(scoreParts[1]);
                                    double percentage = (double) correct / total * 100;
                                    
                                    String resultLine = email + " | " + quizTopic + " | " + score + " | " + percentage + "%";
                                    studentResults[resultCount] = resultLine;
                                    resultCount++;
                                }
                            }
                        }
                    }
                }
            }
            fileScanner.close();
            
            displayStudentResults();
            
        } catch (Exception e) {
            txtResults.setText("Error loading results: " + e.getMessage());
        }
    }
    
    /**
     * Display student results in the text area using simple string concatenation
     */
    private void displayStudentResults() {
        String displayText = "Email | Quiz Topic | Score | Percentage\n";
        displayText = displayText + "=====================================\n";
        
        for (int i = 0; i < resultCount; i++) {
            displayText = displayText + studentResults[i] + "\n";
        }
        
        txtResults.setText(displayText);
    }
    
    /**
     * Filter results based on selected topic using simple string concatenation
     */
    private void filterResults() {
        String selectedTopic = (String) comboFilter.getSelectedItem();
        
        String displayText = "Email | Quiz Topic | Score | Percentage\n";
        displayText = displayText + "=====================================\n";
        
        int count = 0;
        for (int i = 0; i < resultCount; i++) {
            String resultLine = studentResults[i];
            
            if (selectedTopic.equals("All Topics") || resultLine.contains(selectedTopic)) {
                displayText = displayText + resultLine + "\n";
                count++;
            }
        }
        
        if (count == 0) {
            displayText = displayText + "No results match the current filter.\n";
        }
        
        txtResults.setText(displayText);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResultsDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFAQs;
    private javax.swing.JButton BtnHelp;
    private javax.swing.JButton BtnNotes;
    private javax.swing.JButton BtnQuiz;
    private javax.swing.JButton BtnSettings;
    private javax.swing.JLabel LBLLogo2;
    private javax.swing.JLabel LBLlogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> comboFilter;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JScrollPane scrollResults;
    private javax.swing.JTextArea txtResults;
    // End of variables declaration//GEN-END:variables
}
